resnet_depth: 50
train_batch_size: 1024
eval_batch_size: 1024
num_train_images: 1281167
num_eval_images: 50000
train_steps: 112590
base_learning_rate: 0.1
iterations_per_loop: 1251
use_tpu: True
num_cores: 8
enable_lars: False
transpose_input: True
precision: 'bfloat16'
num_label_classes: 1000
use_cache: True
use_async_checkpointing: False
image_size: 224
momentum: 0.9
weight_decay: 0.0001
label_smoothing: 0.0
poly_rate: 0.0
skip_host_call: False
num_parallel_calls: 8
dropblock_groups: ''
dropblock_keep_prob: 0.9
dropblock_size: 7
data_format: 'channels_last'
data_dir: 'gs://jfrankle-imagenet/tensorflow/tensorflow'
lottery_checkpoint_iters: '0,1251,2502,3753,5004,6255,7506,8757,10008,11259,12510,13761,15012,16263,17514,18765,20016,21267,22518,23769,25020,26271,27522,28773,30024,31275,32526,33777,35028,36279,37530,38781,40032,41283,42534,43785,45036,46287,47538,48789,50040,51291,52542,53793,55044,56295,57546,58797,60048,61299,62550,63801,65052,66303,67554,68805,70056,71307,72558,73809,75060,76311,77562,78813,80064,81315,82566,83817,85068,86319,87570,88821,90072,91323,92574,93825,95076,96327,97578,98829,100080,101331,102582,103833,105084,106335,107586,108837,110088,111339,112590' # must be multiples of iterations_per_loop
lottery_results_dir: ''
lottery_prune_at: ''
lottery_pruning_method: 'prune_global_20'
lottery_reset_to: ''
lottery_reset_global_step_to: ''
lottery_force_learning_rate: null
lth_use_random_label: False
lth_no_pruning: False
lth_prediction_result_dir: ''
lottery_force_reprune: False
